# Generated by Django 4.2.4 on 2024-01-12 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="quote_to_tweet",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="tweet_ptr",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="reply_to_tweet",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="tweet_ptr",
        ),
        migrations.RemoveField(
            model_name="retweet",
            name="tweet",
        ),
        migrations.RemoveField(
            model_name="retweet",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="tweet",
            options={"verbose_name": "tweet", "verbose_name_plural": "tweets"},
        ),
        migrations.AddField(
            model_name="tweet",
            name="parent_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="tweet.tweet",
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="type",
            field=models.CharField(
                choices=[
                    ("tweet", "Tweet"),
                    ("reply", "reply"),
                    ("retweet", "retweet"),
                    ("quote", "quote"),
                ],
                default="tweet",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(
                fields=["user", "created_at"], name="tweet_tweet_user_id_21ea6e_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
        migrations.DeleteModel(
            name="Retweet",
        ),
    ]
