# Generated by Django 4.2.4 on 2024-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0002_remove_quote_quote_to_tweet_remove_quote_tweet_ptr_and_more"),
        ("hashtag", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hashtag",
            options={"verbose_name": "hashtag", "verbose_name_plural": "hashtags"},
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="tweet",
            field=models.ManyToManyField(related_name="tweets", to="tweet.tweet"),
        ),
    ]
